version: "3.8"

services:
  db:
    restart: on-failure
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres # TODO: Use private env file
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - db

  server:
    restart: on-failure
    build: ./server
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - db
      - back-tier

  client_mobile:
    restart: on-failure
    build: ./mobile
    volumes:
      - common-volume:/common-volume

  client_web:
    restart: on-failure
    build: ./web
    networks:
      - back-tier
    depends_on:
      - server
      - client_mobile
    volumes:
      - common-volume:/common-volume
    ports:
      - 8081:8081

networks:
  db:
  back-tier:

volumes:
  common-volume:
