version: "3.8"

services:
  db:
    restart: always
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - db

  server:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: server
    image: server_dev
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}?schema=public"
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      WEB_URL: "${WEB_IP}:${WEB_PORT}"
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DISCORD_REDIRECT_URI: "${SERVER_IP}:${SERVER_PORT}/${DISCORD_REDIRECT_URI}"
      SERVER_URL: "${SERVER_IP}:${SERVER_PORT}"
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
    volumes:
      - ./server/src:/app/src
    ports:
      - 8080:8080
    networks:
      - db
      - back-tier

  setup-db:
    restart: on-failure
    image: server_dev
    container_name: setup-db
    depends_on:
      - db
      - server
    command: npm run db:dev:deploy
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}?schema=public"
    networks:
      - db

  client_mobile:
    restart: on-failure
    image: client_mobile_dev
    container_name: client_mobile
    build:
      context: ./mobile
      dockerfile: Dockerfile.dev
    volumes:
      - ./mobile/src:/app/src
    networks:
      - back-tier
    ports:
      - 8083:8083

  client_web:
    restart: always
    container_name: client_web
    image: client_web_dev
    build:
      context: ./web
      dockerfile: Dockerfile
    networks:
      - back-tier
    depends_on:
      - server
      - client_mobile
    environment:
      REACT_APP_SERVER_URL: "${SERVER_IP}:${SERVER_PORT}"
      REACT_APP_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    volumes:
      - ./web/src:/app/src
    ports:
      - 8081:8081

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '8082:80'
    depends_on:
      - db
    networks:
      - db

networks:
  db:
  back-tier:
