version: "3.8"

services:
  db:
    restart: on-failure
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres # TODO: Use private env file
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - network-db

  server:
    restart: on-failure
    depends_on:
      - db
    build: ./server
    networks:
      - network-db
    #   - back-tier
    ports:
      - "8080:8080"

  client_mobile:
    restart: on-failure
    build: ./mobile
    # networks:
    #   - back-tier
    volumes:
      - common-volume:/usr/common-volume

  client_web:
    restart: on-failure
    build: ./web
    # networks:
    #   - back-tier
    depends_on:
      - server
      - client_mobile
    volumes:
      - common-volume:/usr/common-volume
    ports:
      - "8081:8081"

networks:
  network-db:
#   back-tier:

volumes:
  common-volume:
