version: "3.8"

services:
  db:
    restart: always
    container_name: db
    image: postgres:13
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - db

  server:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: server
    image: server_prod
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}?schema=public"
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      WEB_URL: ${WEB_URL}
      REFRESH_TOKEN: ${REFRESH_TOKEN}
      EMAIL: ${EMAIL}
    ports:
      - 8080:8080
    networks:
      - db
      - back-tier

  setup-db:
    restart: on-failure
    image: server_prod
    container_name: setup-db
    depends_on:
      - db
    command: npm run db:dev:deploy
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}?schema=public"
    networks:
      - db

  client_mobile:
    restart: on-failure
    container_name: client_mobile
    build:
      context: ./mobile
      dockerfile: Dockerfile
    volumes:
      - common-volume:/common-volume

  client_web:
    restart: always
    container_name: client_web
    image: client_web_prod
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    networks:
      - back-tier
    depends_on:
      - server
      - client_mobile
    environment:
      REACT_APP_SERVER_URL: ${SERVER_URL}
      REACT_APP_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    volumes:
      - common-volume:/common-volume
    ports:
      - 8081:8081

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '8083:80'
    depends_on:
      - db
    networks:
      - db



networks:
  db:
  back-tier:

volumes:
  common-volume:
