name: Checks

on: [pull_request]

jobs:
  check_linter_server:
    name: Linter for server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        working-directory: ./server
        run: npm install

      - name: Run linter
        working-directory: ./server
        run: npm run lint

  check_tests_server:
    name: Tests for server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        working-directory: ./server
        run: npm install

      - name: Run tests
        working-directory: ./server
        run: npm run test

  check_linter_web:
    name: Linter for web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        working-directory: ./web
        run: npm install

      - name: Run linter
        working-directory: ./web
        run: npm run lint
