name: checks linter

on: [pull_request]

jobs:
  check_linter_server:
    name: Check linter for server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        working-directory: ./server
        run: npm install

      - name: Run linter
        working-directory: ./server
        run: npm run lint
