name: checks linters and tests

on: [pull_request]

jobs:
  check_linter_server:
    name: Check linter for server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        working-directory: ./server
        run: npm install

      - name: Run linter
        working-directory: ./server
        run: npm run lint

  check_tests_server:
    name: Check tests for server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        working-directory: ./server
        run: npm install

      - name: Run tests
        working-directory: ./server
        run: npm run test
