name: mirror

on:
  push:
    branches:
      - main

env:
  MIRROR_URL: "git@github.com:EpitechPromo2026/B-DEV-500-NAN-5-1-area-alexandre.guillard.git"

jobs:
  push_to_mirror:
    name: Pushes the current repository files to a given mirror repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push mirror repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
