FROM node:20 as builder

ENV NODE_ENV production

RUN mkdir common-volume

WORKDIR /app

COPY package*.json ./

RUN npm i

COPY . .

RUN npm run build

FROM node:20 as final

ENV NODE_ENV production

RUN mkdir common-volume

WORKDIR /app

COPY --from=builder /app/build ./build

RUN npm install -g serve

ENV PORT 8081

EXPOSE 8081

CMD ["serve", "-s", "build"]

